/**
 * Application tables (Spec 00 §6). Auth tables live in ./auth.ts and are
 * generated by the Better Auth CLI — never hand-edit that file.
 *
 * Design decisions (project-wide, from Spec 00):
 * - IDs are text nanoid(21), generated app-side via $defaultFn.
 * - Timestamps are integer epoch milliseconds UTC ({ mode: 'timestamp_ms' }),
 *   surfaced as Date in TypeScript.
 * - Money is integers only: total_price_cents (euro cents) and
 *   unit_price_milli (milli-euros per base unit). Never floats.
 * - Text enums are plain text columns typed via $type<> unions from
 *   src/lib/domain/ — no SQLite CHECK constraints, validation happens with
 *   Zod at the boundary before data reaches a repository.
 * - FK actions: user delete cascades everywhere (full account wipe);
 *   product delete is blocked while entries reference it (history must
 *   never silently vanish — archive or merge instead); store/session
 *   deletes set the reference to NULL (entries outlive organizational
 *   metadata).
 *
 * Deviation from Spec 02 §4.2 (documented, verified empirically): the spec
 * text gives price_entries.productId's FK as `onDelete: 'restrict'`. SQLite
 * checks RESTRICT immediately per-row, not deferred to end-of-statement like
 * every other FK action (including the default NO ACTION) — so a single
 * `DELETE FROM users` that cascades to both products and price_entries can
 * fail with a spurious FK violation depending on which sibling cascade
 * SQLite happens to process first, breaking the "user delete cascades
 * everywhere" full-account-wipe guarantee this same spec requires (Spec 02
 * §10.2 "should cascade-delete all user data when the user row is deleted").
 * Omitting onDelete (SQLite's NO ACTION default) keeps the identical
 * user-facing behavior — a direct product delete while entries exist is
 * still blocked — but checks at end-of-statement, so it no longer races the
 * user-cascade's own price_entries cleanup within the same statement.
 */
import { index, integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';
import { nanoid } from 'nanoid';

import type { CategoryId } from '@/lib/domain/categories';
import type { EntrySource, PromoKind, SessionStatus } from '@/lib/domain/entries';
import type { StoreKind } from '@/lib/domain/stores';
import type { UnitKind } from '@/lib/domain/units';
import { users } from './auth';

// Shared column builders keep the five tables visually identical.
const idColumn = () =>
  text('id')
    .primaryKey()
    .$defaultFn(() => nanoid());

const userIdColumn = () =>
  text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' });

const createdAtColumn = () =>
  integer('created_at', { mode: 'timestamp_ms' })
    .notNull()
    .$defaultFn(() => new Date());

const updatedAtColumn = () =>
  integer('updated_at', { mode: 'timestamp_ms' })
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdate(() => new Date());

export const userSettings = sqliteTable('user_settings', {
  // Why: PK == FK — exactly one settings row per user, no surrogate id needed.
  userId: text('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  includePromosInIndex: integer('include_promos_in_index', { mode: 'boolean' })
    .notNull()
    .default(true),
  carryForwardMonths: integer('carry_forward_months').notNull().default(2),
  createdAt: createdAtColumn(),
  updatedAt: updatedAtColumn(),
});

export const stores = sqliteTable(
  'stores',
  {
    id: idColumn(),
    userId: userIdColumn(),
    name: text('name').notNull(),
    chain: text('chain'),
    city: text('city'),
    kind: text('kind').$type<StoreKind>().notNull(),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [index('stores_user_id_idx').on(table.userId)],
);

export const products = sqliteTable(
  'products',
  {
    id: idColumn(),
    userId: userIdColumn(),
    name: text('name').notNull(),
    brand: text('brand'),
    category: text('category').$type<CategoryId>().notNull(),
    unitKind: text('unit_kind').$type<UnitKind>().notNull(),
    notes: text('notes'),
    isArchived: integer('is_archived', { mode: 'boolean' }).notNull().default(false),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [index('products_user_id_idx').on(table.userId)],
);

export const shoppingSessions = sqliteTable(
  'shopping_sessions',
  {
    id: idColumn(),
    userId: userIdColumn(),
    storeId: text('store_id').references(() => stores.id, { onDelete: 'set null' }),
    status: text('status').$type<SessionStatus>().notNull().default('active'),
    startedAt: integer('started_at', { mode: 'timestamp_ms' })
      .notNull()
      .$defaultFn(() => new Date()),
    completedAt: integer('completed_at', { mode: 'timestamp_ms' }),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [index('shopping_sessions_user_id_idx').on(table.userId)],
);

export const priceEntries = sqliteTable(
  'price_entries',
  {
    id: idColumn(),
    userId: userIdColumn(),
    // Why no onDelete (SQLite default NO ACTION, not 'restrict'): see the
    // file-level comment above — this still blocks deleting a product with
    // history, it just checks at end-of-statement instead of per-row so it
    // doesn't race the cascading user-delete's own price_entries cleanup.
    productId: text('product_id')
      .notNull()
      .references(() => products.id),
    storeId: text('store_id').references(() => stores.id, { onDelete: 'set null' }),
    sessionId: text('session_id').references(() => shoppingSessions.id, {
      onDelete: 'set null',
    }),
    recordedAt: integer('recorded_at', { mode: 'timestamp_ms' }).notNull(),
    totalPriceCents: integer('total_price_cents').notNull(),
    packageSize: real('package_size').notNull(),
    unitPriceMilli: integer('unit_price_milli').notNull(),
    isPromo: integer('is_promo', { mode: 'boolean' }).notNull().default(false),
    promoKind: text('promo_kind').$type<PromoKind>(),
    source: text('source').$type<EntrySource>().notNull(),
    currency: text('currency').notNull().default('EUR'),
    photoUrl: text('photo_url'),
    aiConfidence: real('ai_confidence'),
    aiModel: text('ai_model'),
    aiRawJson: text('ai_raw_json'),
    createdAt: createdAtColumn(),
    updatedAt: updatedAtColumn(),
  },
  (table) => [
    // Powers per-product price history and monthly bucketing (Spec 04).
    index('price_entries_user_product_recorded_idx').on(
      table.userId,
      table.productId,
      table.recordedAt,
    ),
    // Powers the /history timeline and cursor pagination.
    index('price_entries_user_recorded_idx').on(table.userId, table.recordedAt),
  ],
);

// Inferred row types — the canonical TypeScript shapes used across layers.
export type UserSettings = typeof userSettings.$inferSelect;
export type Store = typeof stores.$inferSelect;
export type NewStore = typeof stores.$inferInsert;
export type Product = typeof products.$inferSelect;
export type NewProduct = typeof products.$inferInsert;
export type ShoppingSession = typeof shoppingSessions.$inferSelect;
export type NewShoppingSession = typeof shoppingSessions.$inferInsert;
export type PriceEntry = typeof priceEntries.$inferSelect;
export type NewPriceEntry = typeof priceEntries.$inferInsert;
