import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

import { expect, test } from '@playwright/test';

import { SEED_USER_2 } from './fixtures/users';
import { resetReceiptFixtures, seedExtractedReceipt } from './helpers/db';

/*
 * Receipt import E2E suite.
 *
 * Three deliberate choices:
 * - The fixture PDF is SYNTHETIC, generated by scripts/make-receipt-fixture.ts
 *   with invented product names. A real receipt carries a real store, a real
 *   date, a loyalty number and somebody's actual shopping; it must never
 *   enter this repository.
 * - The extraction is seeded into the `receipts` row rather than produced by
 *   a live model call. That call is the one step an E2E run must not make —
 *   it costs money and its answer is not deterministic — and everything
 *   downstream of it (resolution, review, confirm, aliases, entries) is then
 *   exercised for real, against the real database.
 * - The idempotency test uses the REAL route with no mock at all: the hash
 *   check runs before the gateway, so a re-upload of a confirmed receipt is
 *   answered by production code without any AI call.
 *
 * Outcomes are verified against GET /api/export (the database), never
 * against the page alone. The suite runs as the second seed user so it never
 * disturbs the rich dataset the other specs assert on.
 */

test.use({ storageState: 'playwright/.auth/dev2.json' });
// Serial: the second test asserts on the state the first one confirms.
test.describe.configure({ mode: 'serial' });

const FIXTURE_PATH = 'tests/e2e/fixtures/receipt-coop-sample.pdf';
const RECEIPT_ID = 'e2eReceiptFixture0001';
/** 19 August 2026, 18:42 Rome — the date printed on the fixture. */
const PURCHASED_AT = Date.UTC(2026, 7, 19, 16, 42);

/** The extraction the model would have produced from the fixture PDF. */
const EXTRACTION = {
  storeChain: 'Coop',
  storeName: 'Coop Via Fenicottero 12',
  purchasedAt: '2026-08-19T18:42:00',
  receiptTotalCents: 620,
  confidence: 0.93,
  lines: [
    {
      rawLine: 'PASTA FENICOTTERO N5 500G      1,29',
      description: 'Pasta fenicottero n.5 500g',
      brand: null,
      category: 'food',
      quantity: 1,
      quantityKind: 'pieces',
      unitPriceCentsOnReceipt: null,
      lineTotalCents: 129,
      discountCents: 0,
      packageSizeHint: 0.5,
      unitKindHint: 'weight',
      isPromo: false,
      promoKind: null,
      confidence: 0.96,
    },
    {
      rawLine: 'LATTE ORNITORINCO 1L   2 x 1,09  2,18',
      description: 'Latte ornitorinco 1L',
      brand: null,
      category: 'beverages',
      quantity: 2,
      quantityKind: 'pieces',
      unitPriceCentsOnReceipt: 109,
      lineTotalCents: 178,
      discountCents: 40,
      packageSizeHint: 1,
      unitKindHint: 'volume',
      isPromo: true,
      promoKind: 'loyalty',
      confidence: 0.91,
    },
    {
      // No size anywhere and a weighed product: the line the user must fix.
      rawLine: 'QUOKKA FRESCO A PESO             3,10',
      description: 'Quokka fresco',
      brand: null,
      category: 'food',
      quantity: 1,
      quantityKind: 'pieces',
      unitPriceCentsOnReceipt: null,
      lineTotalCents: 310,
      discountCents: 0,
      packageSizeHint: null,
      unitKindHint: 'weight',
      isPromo: false,
      promoKind: null,
      confidence: 0.72,
    },
  ],
};

function fixtureHash(): string {
  return createHash('sha256').update(readFileSync(FIXTURE_PATH)).digest('hex');
}

// beforeAll, not beforeEach: the second test asserts on what the first one
// wrote, so the slate is wiped once per (re)run of the serial group.
test.beforeAll(async () => {
  await resetReceiptFixtures(SEED_USER_2.email);
});

test('should read a receipt, fix the flagged line and confirm it into the database', async ({
  page,
}) => {
  await seedExtractedReceipt(SEED_USER_2.email, {
    id: RECEIPT_ID,
    contentHash: fixtureHash(),
    purchasedAt: PURCHASED_AT,
    receiptTotalCents: 620,
    extraction: EXTRACTION,
  });

  // The upload screen's own job — picking a file and posting it — is real;
  // only the model's answer is substituted, by handing back the receipt id
  // whose extraction is already on file.
  await page.route('**/api/extract-receipt', (route) =>
    route.fulfill({ status: 200, json: { receiptId: RECEIPT_ID } }),
  );

  await page.goto('/add/receipt');
  await expect(page.getByTestId('receipt-dropzone')).toBeVisible();
  await page.setInputFiles('[data-testid="receipt-file-input"]', FIXTURE_PATH);
  await page.getByTestId('receipt-submit').click();

  await expect(page).toHaveURL(/\/add\/receipt\/review/);
  await expect(page.getByTestId('receipt-line-card')).toHaveCount(3);

  // The weighed line has no size anywhere, so it blocks confirmation — and
  // only it: the other two resolved themselves.
  const blockedCard = page.locator('[data-testid="receipt-line-card"][data-status="needs-size"]');
  await expect(blockedCard).toHaveCount(1);

  /*
   * Confirm is not disabled — it names the line instead. What matters is the
   * guarantee, not the button state: pressing it with an unfinished line
   * scrolls to that line, says what it needs, and writes nothing.
   */
  await page.getByTestId('receipt-confirm').click();
  await expect(blockedCard.getByTestId('receipt-blocking-reason')).toBeVisible();
  await expect(page).toHaveURL(/\/add\/receipt\/review/);
  const beforeFix = await (await page.request.get('/api/export')).json();
  expect(
    beforeFix.entries.filter((entry: { source: string }) => entry.source === 'receipt'),
  ).toHaveLength(0);

  await blockedCard.getByTestId('receipt-field-size').fill('0,4');
  await expect(page.getByTestId('receipt-blocking-reason')).toHaveCount(0);

  await page.getByTestId('receipt-confirm').click();
  await expect(page).toHaveURL(/\/history/);

  const exportResponse = await page.request.get('/api/export');
  expect(exportResponse.status()).toBe(200);
  const payload = await exportResponse.json();
  expect(payload.schemaVersion).toBe(2);

  const receiptEntries = payload.entries.filter(
    (entry: { source: string }) => entry.source === 'receipt',
  );
  expect(receiptEntries).toHaveLength(3);
  for (const entry of receiptEntries) {
    expect(entry.receiptId).toBe(RECEIPT_ID);
    // A receipt is never stored as a photo.
    expect(entry.photoUrl).toBeNull();
    expect(entry.aiModel).toBe('claude-haiku-4-5');
    expect(new Date(entry.recordedAt).getTime()).toBe(PURCHASED_AT);
  }

  // "2 x 1,09" is ONE observation of the price 1,09 bought twice.
  const latte = receiptEntries.find((entry: { quantity: number }) => entry.quantity === 2);
  expect(latte).toMatchObject({ totalPriceCents: 89, unitPriceMilli: 890, isPromo: true });

  // The line the user fixed: 3,10 for 0,4 kg is 7,75 €/kg.
  const quokka = receiptEntries.find(
    (entry: { totalPriceCents: number }) => entry.totalPriceCents === 310,
  );
  expect(quokka).toMatchObject({ packageSize: 0.4, unitPriceMilli: 7750 });

  // Every confirmed line was remembered for the next receipt of this chain.
  expect(payload.productAliases).toHaveLength(3);
  expect(payload.productAliases.map((alias: { alias: string }) => alias.alias).sort()).toEqual([
    'latte ornitorinco 1l',
    'pasta fenicottero n5 500g',
    'quokka fresco a peso',
  ]);

  const confirmedReceipt = payload.receipts.find(
    (receipt: { id: string }) => receipt.id === RECEIPT_ID,
  );
  expect(confirmedReceipt).toMatchObject({ status: 'confirmed', lineCount: 3 });
});

test('should refuse a re-upload of a receipt that was already imported', async ({ page }) => {
  // No route mock at all: the content-hash check runs before the gateway, so
  // production code answers this without touching Anthropic.
  await page.goto('/add/receipt');
  await expect(page.getByTestId('receipt-dropzone')).toBeVisible();
  await page.setInputFiles('[data-testid="receipt-file-input"]', FIXTURE_PATH);
  await page.getByTestId('receipt-submit').click();

  await expect(page.getByTestId('receipt-error')).toBeVisible();
  await expect(page.getByTestId('receipt-error')).toContainText('già stato importato');
  await expect(page).toHaveURL(/\/add\/receipt$/);

  // Nothing was added by the second attempt.
  const payload = await (await page.request.get('/api/export')).json();
  expect(
    payload.entries.filter((entry: { source: string }) => entry.source === 'receipt'),
  ).toHaveLength(3);
});

/*
 * A till prints the same article twice as readily as it prints "2 x". Both
 * are one price paid twice, and the import has to land them the same way —
 * otherwise the same shopping trip weighs twice as much in the index
 * depending on how the shop chose to print it.
 *
 * Its own receipt id, hash and spy word ("capibara"), so it neither collides
 * with the serial pair above nor lets its product capture their lines.
 */
const DUPLICATE_RECEIPT_ID = 'e2eReceiptDuplicate01';
const DUPLICATE_PURCHASED_AT = Date.UTC(2026, 7, 20, 16, 42);

const PESTO_LINE = {
  rawLine: 'PESTO CAPIBARA 190G            2,49',
  description: 'Pesto capibara 190g',
  brand: null,
  category: 'food' as const,
  quantity: 1,
  quantityKind: 'pieces' as const,
  unitPriceCentsOnReceipt: null,
  lineTotalCents: 249,
  discountCents: 0,
  packageSizeHint: 0.19,
  unitKindHint: 'weight' as const,
  isPromo: false,
  promoKind: null,
  confidence: 0.95,
};

test('should fold two identical printed lines into one observation bought twice', async ({
  page,
}) => {
  await seedExtractedReceipt(SEED_USER_2.email, {
    id: DUPLICATE_RECEIPT_ID,
    contentHash: `duplicate-${DUPLICATE_RECEIPT_ID}`,
    purchasedAt: DUPLICATE_PURCHASED_AT,
    receiptTotalCents: 498,
    extraction: {
      storeChain: 'Coop',
      storeName: 'Coop Via Fenicottero 12',
      purchasedAt: '2026-08-20T18:42:00',
      receiptTotalCents: 498,
      confidence: 0.93,
      lines: [PESTO_LINE, PESTO_LINE],
    },
  });

  await page.route('**/api/extract-receipt', (route) =>
    route.fulfill({ status: 200, json: { receiptId: DUPLICATE_RECEIPT_ID } }),
  );

  await page.goto('/add/receipt');
  await expect(page.getByTestId('receipt-dropzone')).toBeVisible();
  await page.setInputFiles('[data-testid="receipt-file-input"]', FIXTURE_PATH);
  await page.getByTestId('receipt-submit').click();

  await expect(page).toHaveURL(/\/add\/receipt\/review/);

  // One card, not two — and it says so, so the paper can still be checked
  // against the screen line by line.
  await expect(page.getByTestId('receipt-line-card')).toHaveCount(1);
  await expect(page.getByTestId('receipt-merged-lines')).toHaveText('2 righe uguali');

  // The money is unchanged by the fold: 2,49 x 2 — said on the card too, so
  // the line can be checked against the total printed on the paper.
  await expect(page.getByTestId('receipt-total')).toContainText('4,98');
  await expect(page.getByTestId('receipt-line-total')).toContainText('2 × 2,49');
  await expect(page.getByTestId('receipt-line-total')).toContainText('4,98');

  await page.getByTestId('receipt-confirm').click();
  await expect(page).toHaveURL(/\/history/);

  const payload = await (await page.request.get('/api/export')).json();
  const entries = payload.entries.filter(
    (entry: { receiptId: string }) => entry.receiptId === DUPLICATE_RECEIPT_ID,
  );
  expect(entries).toHaveLength(1);
  expect(entries[0]).toMatchObject({
    quantity: 2,
    // The price of ONE jar; the quantity carries the rest.
    totalPriceCents: 249,
    packageSize: 0.19,
    unitPriceMilli: 13105,
  });
});

/*
 * The failure this suite exists to catch after the fact: a till printed six
 * identical lines and the model handed back seven. Every line is plausible
 * on its own, so nothing per-line can see it — only the printed total can,
 * and only if the screen reconciles against the lines AS EDITED.
 *
 * Its own spy word ("narvalo"), disjoint from the other receipts here
 * (AGENTS.md §4.60).
 */
const OVERCOUNT_RECEIPT_ID = 'e2eReceiptOvercount01';
const OVERCOUNT_PURCHASED_AT = Date.UTC(2026, 7, 21, 16, 42);

const NARVALO_LINE = {
  // Deliberately unlike every other product this user owns: a line the fuzzy
  // matcher half-recognises blocks on `needs-product`, which is a different
  // test than this one (AGENTS.md §4.60).
  rawLine: 'CREMA NARVALO 250G             1,64',
  description: 'Crema narvalo 250g',
  brand: null,
  category: 'food' as const,
  quantity: 1,
  quantityKind: 'pieces' as const,
  unitPriceCentsOnReceipt: null,
  lineTotalCents: 164,
  discountCents: 0,
  packageSizeHint: 0.25,
  unitKindHint: 'weight' as const,
  isPromo: false,
  promoKind: null,
  confidence: 0.95,
};

test('should point at the line whose extra package explains the total gap', async ({ page }) => {
  await seedExtractedReceipt(SEED_USER_2.email, {
    id: OVERCOUNT_RECEIPT_ID,
    contentHash: `overcount-${OVERCOUNT_RECEIPT_ID}`,
    purchasedAt: OVERCOUNT_PURCHASED_AT,
    // Three lines extracted, two jars actually paid for.
    receiptTotalCents: 328,
    extraction: {
      storeChain: 'Coop',
      storeName: 'Coop Via Fenicottero 12',
      purchasedAt: '2026-08-21T18:42:00',
      receiptTotalCents: 328,
      confidence: 0.93,
      lines: [NARVALO_LINE, NARVALO_LINE, NARVALO_LINE],
    },
  });

  await page.route('**/api/extract-receipt', (route) =>
    route.fulfill({ status: 200, json: { receiptId: OVERCOUNT_RECEIPT_ID } }),
  );

  await page.goto('/add/receipt');
  await expect(page.getByTestId('receipt-dropzone')).toBeVisible();
  await page.setInputFiles('[data-testid="receipt-file-input"]', FIXTURE_PATH);
  await page.getByTestId('receipt-submit').click();

  await expect(page).toHaveURL(/\/add\/receipt\/review/);

  // The gap is named, in euros and in packages of the line that carries it.
  await expect(page.getByTestId('receipt-total-difference')).toContainText('1,64');
  await expect(page.getByTestId('receipt-extra-packages')).toContainText('1 confezione');
  await expect(page.getByTestId('receipt-extra-packages')).toContainText('Crema narvalo');

  // One tap on the stepper closes it — which is the whole point of
  // reconciling against the lines as edited rather than as extracted.
  await page.getByRole('button', { name: 'Confezioni −1' }).click();
  await expect(page.getByTestId('receipt-header-warning')).toHaveCount(0);
  await expect(page.getByTestId('receipt-lines-total')).toContainText('3,28');

  await page.getByTestId('receipt-confirm').click();
  await expect(page).toHaveURL(/\/history/);

  const payload = await (await page.request.get('/api/export')).json();
  const entries = payload.entries.filter(
    (entry: { receiptId: string }) => entry.receiptId === OVERCOUNT_RECEIPT_ID,
  );
  expect(entries).toHaveLength(1);
  expect(entries[0]).toMatchObject({ quantity: 2, totalPriceCents: 164 });
});
