import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

import { expect, test } from '@playwright/test';

import { SEED_USER_2 } from './fixtures/users';
import { resetReceiptFixtures, seedExtractedReceipt } from './helpers/db';

/*
 * Receipt import E2E suite (Spec 07 §11.7).
 *
 * Three deliberate choices:
 * - The fixture PDF is SYNTHETIC, generated by scripts/make-receipt-fixture.ts
 *   with invented product names. A real receipt carries a real store, a real
 *   date, a loyalty number and somebody's actual shopping; it must never
 *   enter this repository.
 * - The extraction is seeded into the `receipts` row rather than produced by
 *   a live model call. That call is the one step an E2E run must not make —
 *   it costs money and its answer is not deterministic — and everything
 *   downstream of it (resolution, review, confirm, aliases, entries) is then
 *   exercised for real, against the real database.
 * - The idempotency test uses the REAL route with no mock at all: the hash
 *   check runs before the gateway, so a re-upload of a confirmed receipt is
 *   answered by production code without any AI call.
 *
 * Outcomes are verified against GET /api/export (the database), never
 * against the page alone. The suite runs as the second seed user so it never
 * disturbs the rich dataset the other specs assert on.
 */

test.use({ storageState: 'playwright/.auth/dev2.json' });
// Serial: the second test asserts on the state the first one confirms.
test.describe.configure({ mode: 'serial' });

const FIXTURE_PATH = 'tests/e2e/fixtures/receipt-coop-sample.pdf';
const RECEIPT_ID = 'e2eReceiptFixture0001';
/** 19 August 2026, 18:42 Rome — the date printed on the fixture. */
const PURCHASED_AT = Date.UTC(2026, 7, 19, 16, 42);

/** The extraction the model would have produced from the fixture PDF. */
const EXTRACTION = {
  storeChain: 'Coop',
  storeName: 'Coop Via Fenicottero 12',
  purchasedAt: '2026-08-19T18:42:00',
  receiptTotalCents: 620,
  confidence: 0.93,
  lines: [
    {
      rawLine: 'PASTA FENICOTTERO N5 500G      1,29',
      description: 'Pasta fenicottero n.5 500g',
      brand: null,
      category: 'food',
      quantity: 1,
      quantityKind: 'pieces',
      unitPriceCentsOnReceipt: null,
      lineTotalCents: 129,
      discountCents: 0,
      packageSizeHint: 0.5,
      unitKindHint: 'weight',
      isPromo: false,
      promoKind: null,
      confidence: 0.96,
    },
    {
      rawLine: 'LATTE ORNITORINCO 1L   2 x 1,09  2,18',
      description: 'Latte ornitorinco 1L',
      brand: null,
      category: 'beverages',
      quantity: 2,
      quantityKind: 'pieces',
      unitPriceCentsOnReceipt: 109,
      lineTotalCents: 178,
      discountCents: 40,
      packageSizeHint: 1,
      unitKindHint: 'volume',
      isPromo: true,
      promoKind: 'loyalty',
      confidence: 0.91,
    },
    {
      // No size anywhere and a weighed product: the line the user must fix.
      rawLine: 'QUOKKA FRESCO A PESO             3,10',
      description: 'Quokka fresco',
      brand: null,
      category: 'food',
      quantity: 1,
      quantityKind: 'pieces',
      unitPriceCentsOnReceipt: null,
      lineTotalCents: 310,
      discountCents: 0,
      packageSizeHint: null,
      unitKindHint: 'weight',
      isPromo: false,
      promoKind: null,
      confidence: 0.72,
    },
  ],
};

function fixtureHash(): string {
  return createHash('sha256').update(readFileSync(FIXTURE_PATH)).digest('hex');
}

// beforeAll, not beforeEach: the second test asserts on what the first one
// wrote, so the slate is wiped once per (re)run of the serial group.
test.beforeAll(async () => {
  await resetReceiptFixtures(SEED_USER_2.email);
});

test('should read a receipt, fix the flagged line and confirm it into the database', async ({
  page,
}) => {
  await seedExtractedReceipt(SEED_USER_2.email, {
    id: RECEIPT_ID,
    contentHash: fixtureHash(),
    purchasedAt: PURCHASED_AT,
    receiptTotalCents: 620,
    extraction: EXTRACTION,
  });

  // The upload screen's own job — picking a file and posting it — is real;
  // only the model's answer is substituted, by handing back the receipt id
  // whose extraction is already on file.
  await page.route('**/api/extract-receipt', (route) =>
    route.fulfill({ status: 200, json: { receiptId: RECEIPT_ID } }),
  );

  await page.goto('/add/receipt');
  await expect(page.getByTestId('receipt-dropzone')).toBeVisible();
  await page.setInputFiles('[data-testid="receipt-file-input"]', FIXTURE_PATH);
  await page.getByTestId('receipt-submit').click();

  await expect(page).toHaveURL(/\/add\/receipt\/review/);
  await expect(page.getByTestId('receipt-line-card')).toHaveCount(3);

  // The weighed line has no size anywhere, so it blocks confirmation — and
  // only it: the other two resolved themselves.
  const blockedCard = page.locator('[data-testid="receipt-line-card"][data-status="needs-size"]');
  await expect(blockedCard).toHaveCount(1);
  await expect(page.getByTestId('receipt-confirm')).toBeDisabled();

  await blockedCard.getByTestId('receipt-field-size').fill('0,4');
  await expect(page.getByTestId('receipt-confirm')).toBeEnabled();

  await page.getByTestId('receipt-confirm').click();
  await expect(page).toHaveURL(/\/history/);

  const exportResponse = await page.request.get('/api/export');
  expect(exportResponse.status()).toBe(200);
  const payload = await exportResponse.json();
  expect(payload.schemaVersion).toBe(2);

  const receiptEntries = payload.entries.filter(
    (entry: { source: string }) => entry.source === 'receipt',
  );
  expect(receiptEntries).toHaveLength(3);
  for (const entry of receiptEntries) {
    expect(entry.receiptId).toBe(RECEIPT_ID);
    // A receipt is never stored as a photo (Spec 07 §5.2).
    expect(entry.photoUrl).toBeNull();
    expect(entry.aiModel).toBe('claude-haiku-4-5');
    expect(new Date(entry.recordedAt).getTime()).toBe(PURCHASED_AT);
  }

  // "2 x 1,09" is ONE observation of the price 1,09 bought twice.
  const latte = receiptEntries.find((entry: { quantity: number }) => entry.quantity === 2);
  expect(latte).toMatchObject({ totalPriceCents: 89, unitPriceMilli: 890, isPromo: true });

  // The line the user fixed: 3,10 for 0,4 kg is 7,75 €/kg.
  const quokka = receiptEntries.find(
    (entry: { totalPriceCents: number }) => entry.totalPriceCents === 310,
  );
  expect(quokka).toMatchObject({ packageSize: 0.4, unitPriceMilli: 7750 });

  // Every confirmed line was remembered for the next receipt of this chain.
  expect(payload.productAliases).toHaveLength(3);
  expect(payload.productAliases.map((alias: { alias: string }) => alias.alias).sort()).toEqual([
    'latte ornitorinco 1l',
    'pasta fenicottero n5 500g',
    'quokka fresco a peso',
  ]);

  const confirmedReceipt = payload.receipts.find(
    (receipt: { id: string }) => receipt.id === RECEIPT_ID,
  );
  expect(confirmedReceipt).toMatchObject({ status: 'confirmed', lineCount: 3 });
});

test('should refuse a re-upload of a receipt that was already imported', async ({ page }) => {
  // No route mock at all: the content-hash check runs before the gateway, so
  // production code answers this without touching Anthropic.
  await page.goto('/add/receipt');
  await expect(page.getByTestId('receipt-dropzone')).toBeVisible();
  await page.setInputFiles('[data-testid="receipt-file-input"]', FIXTURE_PATH);
  await page.getByTestId('receipt-submit').click();

  await expect(page.getByTestId('receipt-error')).toBeVisible();
  await expect(page.getByTestId('receipt-error')).toContainText('già stato importato');
  await expect(page).toHaveURL(/\/add\/receipt$/);

  // Nothing was added by the second attempt.
  const payload = await (await page.request.get('/api/export')).json();
  expect(
    payload.entries.filter((entry: { source: string }) => entry.source === 'receipt'),
  ).toHaveLength(3);
});
